spring:
  application:
    name: ms-entreprise
  datasource:
    url: jdbc:mysql://mysql:3306/entreprise_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 9091
